# Suppress findings from ASH tool's own test data
suppressions:
  - scanner: checkov
    path_pattern: "ash-security-scan/ash-tool/tests/test_data/**"
    reason: "Test data from ASH security scanner tool itself"
  - scanner: detect-secrets
    path_pattern: "ash-security-scan/ash-tool/tests/test_data/**"
    reason: "Test data from ASH security scanner tool itself"
  - scanner: checkov
    path_pattern: "ash-security-scan/scanners/**"
    reason: "ASH scan output directory"
  - scanner: detect-secrets
    path_pattern: "ash-security-scan/scanners/**"
    reason: "ASH scan output directory"
